### ISSUE TITLE
Missing File: gbborder.h

### ISSUE THREAD

**Issue by 32teeth** [Ryuzaki-MrL/Espeon#5]
Upon Compile

```
gbfiles.h:24:23: fatal error: gbborder.h: No such file or directory
compilation terminated.
exit status 1
gbborder.h: No such file or directory
```

**Comment by Ryuzaki-MrL** [comment]
For both this and #4 comment out these 2 lines:
https://github.com/Ryuzaki-MrL/Espeon/blob/master/gbfiles.h#L6L7

These are optional and I can't provide these files myself due to copyright.
