### ISSUE TITLE
It works :)

### ISSUE THREAD

**Issue by pierrebak** [Ryuzaki-MrL/Espeon#9]
found my way, working fine now :)
have a nice week-end.

**Comment by VeronW** [comment]
Care to share what you have done to make it work?

**Comment by pierrebak** [comment]
Hello,
Yes, actually it as very simple.
I just flashed the bin files using ESP32 flasher and roms are loaded from the SD card.
Thanks and have a nice week-end.



    Le vendredi 4 décembre 2020 à 19:39:32 UTC+1, VeronW <notifications@github.com> a écrit :  
 
 


Care to share what you have done to make it work?

**Comment by VeronW** [comment]
Thanks!
